### ISSUE TITLE
Replace all $ in .md to $$ to efficiently convert Latex equations using MathJax

### ISSUE THREAD

**Issue by vishakha-lall** [aimacode/aima-exercises#20]
In order to render the Latex math equations using MathJax, the equations must be surrounded by $$. A simple replace all in the .md files would work. I have attached some screenshots for demonstration.
With $
![image](https://user-images.githubusercontent.com/31643223/37250241-1fc6c8ec-251e-11e8-9ebb-a0b388ee0f4f.png)
With $$
![image](https://user-images.githubusercontent.com/31643223/37250234-08de9c86-251e-11e8-8925-8c2dd4b10501.png)

**Comment by Nalinc** [comment]
> In order to render the Latex math equations using MathJax, the equations must be surrounded by $$

@vishakha-lall This is **not** true. MathJax Supports both inline and block-level support for mathematical equations. Generally `$` is used for inline mathematical equations and `$$` is for block-level equations, but you can change it in configuration. They both serve different purposes. The reason you are getting this issue is probably because of the way you are configuring MathJax. Can you share how you are currently configuring MathJax?

Replacing `$` with `$$` in markdown files is **not** required and shouldn't be done. It'll break things in later chapters where both inline and block equations are being used!

**Comment by vishakha-lall** [comment]
Thank you @Nalinc , I realised that the default settings of MathJax were configured that way. I have now modified the configuration to this, and it works. :)
![image](https://user-images.githubusercontent.com/31643223/37251551-24e5e460-2538-11e8-97fc-02512502abb9.png)

**Comment by Nalinc** [comment]
@vishakha-lall Yes, this is correct :-)

**Comment by Nalinc** [comment]
@vishakha-lall Now that it is established that markdowns shouldn't be changed, can you close this issue?
