### ISSUE TITLE
GSoC 2019 Onboarding tasks

### ISSUE THREAD

**Issue by Nalinc** [aimacode/aima-exercises#36]
Share your progress (queries, screenshots, suggestions, hurdles) on GSoC 2019 [onboarding tasks](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-On-boarding-Tasks) here. If you face any difficulties, discuss here instead of opening a new issue. Asking questions does not define your intelligence. It reflects your desire to learn and gives the best evidence of understanding. This is what we are looking for in potential GSoC students.

**Comment by infparadox** [comment]
Hi @Nalinc , I cloned the project and ran the project succesfully. Currently , I am trying to understand the codebase and I thought some features which can be added on the website :
**Suggestions :** 
- Currently , for navigating from current question to next question in a chapter , we need to go back and then navigate to it . It would be good if we can make a navigation bar for each chapter through which we can directly navigate to the questions in the current chapter(As most of us prefer to do questions sequentially from a chapter).

- For the table of contents page , dropdown can be implemented so that we can directly navigate to the questions or subsections of interest.

- For adding new exercises , answers I think we can create a new file corresponding to the latest number and use the existing edit feature(implemented by you) or we can create a new one and take input and save in real time.

**Doubts:**

- For each exercise we need a unique identifer , do we need to use random numbers + hash function for this or like simple pattern/counter can be used.

**Comment by zeph1yr** [comment]
Not sure if this is the right place to put up this question but under AIMA-Exercises the required skills are mentioned to be testing and user interface design. Can you please elaborate on these skills and how they will be applied on AIMA-Exercises.

**Comment by Nalinc** [comment]
@zeph1yr It is indeed the right thread to ask things related to GSoC. [Check out the potential tasks that we wish to work on during summer](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-Proposal-Template#potential-tasks-that-we-look-to-work-on-for-the-summer). You'll see that many of the intented tasks require the skills to design interfaces/components. Further, we want to have some unit tests (implemented either as separate test-scripts or pre-commit hooks) to ensure that the future changes in AIMA Exercises follow the right structure and cover essential things.

@infparadox I like your suggestions. Feel free to include them in your proposal, but make sure you give more weightage to tasks that we have listed. 

Note: Do not send pull-requests related to any of the tasks mentioned above. Follow the [onboarding tasks](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-On-boarding-Tasks) tasks first to understand the project structure and suggest changes based on that.

**Comment by deepaklorkhatri007** [comment]
@Nalinc index.html uses layout: post and post uses layout: default but files index.html and default.html have script tag for jquery, firebase.js and config.js which makes the page 2x the size and thus take more time to load :)
![screenshot from 2019-03-08 11-37-34](https://user-images.githubusercontent.com/20015794/54010997-e8507e80-4196-11e9-968e-c3d356070afa.png)

**Comment by deepaklorkhatri007** [comment]
@Nalinc index.html uses layout: post and post uses layout: default but files index.html and default.html have script tag for jquery, firebase.js and config.js :)
![screenshot from 2019-03-08 11-37-34](https://user-images.githubusercontent.com/20015794/54011147-7cbae100-4197-11e9-889a-1ee88aa282db.png)

**Comment by deepaklorkhatri007** [comment]
@Nalinc I think we need something bit robust than this upvote button anyone can write a simple script in python for this button click event making site slow for others or even worse. can you please tell me why we even need an upvote button on our site? 
![screenshot from 2019-03-08 19-58-30](https://user-images.githubusercontent.com/20015794/54034613-515ae500-41dd-11e9-86d8-6556d5069126.png)

**Comment by deepaklorkhatri007** [comment]
@Nalinc you have integrated Disqus commenting system on the project, I don't really get this idea of comments on exercise website. In my opinion, exercises are meant to be solved by individuals by exploring the book and comments makes it tempting for them to see the answers/clues and really that ruins the whole learning process. well, that's just my opinion please provide some insight on why you used it thanks :)

**Comment by deepaklorkhatri007** [comment]
Hey, @Nalinc can you please tell me the use of file _includes/aima_toc.html, this file contains the chapter list which is also present in the ~/index.html if the code is present in aima_toc.html why haven't you just put {{ include aima_toc.html}} in the ~/index.html.

**Comment by Nalinc** [comment]
> index.html uses layout: post and post uses layout: default but files index.html and default.html have script tag

@deepaklorkhatri007  You're right, there is some redundant code in index.html for script tags. However, I don't see multiple files in my chrome developer console. Can you please specify if you found it on the local development server or in the production? If it was local, please specify what Jekyll version do you have? What OS/browser (version) did you test it on?

> why we even need an upvote button on our site?
>  I don't really get this idea of comments on exercise website.

AIMA Exercises is not only meant to serve static exercises but to support the interactive component for students and instructors visiting the platform. Rating question and supporting comments are thus two of the primary things. Consider an FAQ website with something like StackOverflow. While the former only lists some question-answering pairs, latter allows the users to add new questions, rate them, and have separate discussions on every question and the submitted answer. *We do not want AIMA Exercises to be an FAQ website*. So even though we have the answer-key for all the exercise questions, we would rather want users to submit their answers and have discussions over them.  However, as you pointed, we do have issues with current implementation and would like to have a more robust rating mechanism with better commenting support. The catch is, we do not want a heavy backend server to host AIMA Exercises or pay for servers. So we'll keep Github Pages for hosting the exercises. For rating and commenting, we're using firebase functions and Disqus commenting system, but we're looking for better (free) alternatives.

> can you please tell me the use of file _includes/aima_toc.html

It is primarily used to show the (collapsable) Table-of-Contents panel while viewing an exercise. As you mentioned, few lines in ~/index.html seem redundant. You may send a pull-request to fix this and the first issue mentioned above. Just make sure everything works before sending the PR.

**Comment by deepaklorkhatri007** [comment]
Hey @Nalinc, I have one more question to ask when we click __**1. Introduction**__  from home page to the exercise page then we click __**Exercise 1.1**__ then we get to answer and request answer page and then when we click __**Exercise 1.1**__ again it takes us to 404.html why is that so? do we have something remaining to implement there?

**Comment by deepaklorkhatri007** [comment]
> So even though we have the answer-key for all the exercise questions, we would rather want users to submit their answers and have discussions over them.
hey, @Nalinc can't we just include Disqus on the answer and request answer page rather than having two different threads, one for the entire chapter and one for specific exercise from the chapter.  if the one on the chapter page is for new exercise for the chapter, don't you think it would be better to have a button for GitHub issue just like we have for the request answer button. because getting back to comments now and then for the new exercise request would be a tedious task.

**Comment by deepaklorkhatri007** [comment]
> So even though we have the answer key for all the exercise questions, we would rather want users to submit their answers and have discussions over them.

hey, @Nalinc can't we just include Disqus on the answer and request answer page rather than having two different threads, one for the entire chapter and one for specific exercise from the chapter. if the one on the chapter page is for new exercise for the chapter, don't you think it would be better to have a button for GitHub issue just like we have for the request answer button. because getting back to comments now and then for the new exercise request would be a tedious task.

**Comment by deepaklorkhatri007** [comment]
> For rating and commenting, we're using firebase functions and Disqus commenting system, but we're looking for better (free) alternatives.

I totally agree and I think we can use this method of creating a GitHub hosted commenting system which is explained here https://github.com/wireddown/ghpages-ghcomments.

**Comment by deepaklorkhatri007** [comment]
Hey @Nalinc, you have included this conditional code for the table of content that if we are on the home page don't show the button to reveal out the table of content but the home page already contains the same list of chapter present in aima-toc.html which makes our home page have the same code (chapter list) present 2x. we need something better than just hiding the table of content button there :)

**Comment by deepaklorkhatri007** [comment]
@Nalinc can you please give us some documentation on this project because I am finding repetitive code everywhere in the project, some insight might help us deal better to solve these issues :)

![Screenshot from 2019-03-10 13-50-16](https://user-images.githubusercontent.com/20015794/54082421-854c1c80-433b-11e9-9233-ee2f5fb8d01f.png)

> few lines in ~/index.html seem redundant. You may send a pull request to fix this

I have made a pull request for this (#41)

**Comment by sachin10101998** [comment]
Hi @Nalinc , 
(i) I was going through the  "Potential tasks that we look to work on for the summer."  on the proposal template page and found a task related to bookmarking particular questions by storing them in Local Storage of browser. Instead of implementing it in local storage could we go for dedicated Django backend with MySQL database providing the moderators an admin interface for adding exercises and solutions in the database and personal accounts to all the clients/students/readers. This way the clients/readers/students can not only bookmark the questions but can also practice the questions and check if their answer matches with the correct answer and thus keeping a check on their progress in different chapters. 
(ii) We can implement a points system where the account holder gets a certain number of points on correctly solving a question. Getting higher ranks and getting to top positions in rankings acts as a motivation for constant hard work and thus attracting a larger pool of AI enthusiasts to the exercises website. 
Please do let me know your views on it.
Regards

**Comment by sachin10101998** [comment]
Hi @Nalinc 
I was going through the hosted website "https://aimacode.github.io/aima-exercises/" and found that when we click on Part V Chapter 18, named, Learning from examples, it gave me error 404 Page not found. The other chapters are working fine. The relevant screenshots are attached. The concerned link showing the error is "https://aimacode.github.io/aima-exercises/concept-learning-exercises/" .
![Screenshot (283)](https://user-images.githubusercontent.com/34926285/54317046-35ee4080-4608-11e9-9de3-dce46c7117be.png)
When I cloned the repository, I can see the exercises in the concept-leaning-exercises folder, but it's showing error page when opened through the Aima exercises production page. Should I start working to fix this issue and send a Pr for the same?

**Comment by sachin10101998** [comment]
Hi, @Nalinc  I was going through the codebase and found that in Chapter 2 Jupyter notebook files, Question 1 had been presented as an introduction to exercises and the second question was numbered 2.1. Similarly, the third question was numbered as 2.2 and so on. 
![Screenshot (290)](https://user-images.githubusercontent.com/34926285/54490734-7f77ad80-48de-11e9-9ab9-372825bc68a5.png)
I have resolved this issue and sent a pull request regarding the same. Please look into it. 
Regards

**Comment by sachin10101998** [comment]
Hi, @Nalinc  I started working on a few user interface designs for Aimacode and made this one inspired by Brilliant. This page is for showing the Chapter list. I've made some other designs too which I'll be adding to this comment only. Please let me know your views about the ones I'd have already posted by the time you visit the thread.
![aima1](https://user-images.githubusercontent.com/34926285/54490807-29efd080-48df-11e9-934c-945afc20ad5e.jpg)

**Comment by sachin10101998** [comment]
> hey, @Nalinc can't we just include Disqus on the answer and request answer page rather than having two different threads, one for the entire chapter and one for specific exercise from the chapter. if the one on the chapter page is for new exercise for the chapter, don't you think it would be better to have a button for GitHub issue just like we have for the request answer button. because getting back to comments now and then for the new exercise request would be a tedious task.

Hello @deepaklorkhatri007 I believe that different threads of disqus on chapter page and exercise page serves the purpose of demarcation between comments in general about whole chapter or reviews regarding the chapter as a whole, whereas the comment thread on an exercise page would serve for discussions regarding hurdles faced in that particular exercise. It's perfectly cool to have different threads because they serve different purposes.  

> I don't really get this idea of comments on exercise website.

@deepaklorkhatri007  I believe that people find it easier to just leave a comment and rely on a contributor to explain a problem rather than consulting the documentation. I consider doing everything you can to make people find their own answers a strong part of defensive open source.

>@Nalinc can you please give us some documentation on this project because I am finding repetitive code everywhere in the project

@deepaklorkhatri007 , you may consider going through the closed pull requests and closed issues. I went through them and that helped me a lot in understanding why the technologies which are currently being used in Aimacode Exercises were adopted in first place. The threads there are bit long, but it helps a lot in understanding why the codebase is like the way it is right now. Hope that helps.

**Comment by sachin10101998** [comment]
(i) @Nalinc I went through the codebase and found that you had linked CSS files after some JS files. The optimum way should be to load CSS files before JS ones. I have sent a pull request regarding the same for the all chapters list and pages showing all the exercises. I'll do it for individual exercises too if the request gets merged.
(ii) Another thing that I wanted to mention is that you haven't minified the JS files. Minifying the JS files will reduce their size by 40.1KiB (15% reduction). I can send a pull request for the same if you like it.
(iii) The CSS files and Firebase JS files are cacheable resources and we can leverage browser caching for these. This will help the visitor in preventing reloading same files again and again. I can make the required changes in htaccess files and send a pull request regarding the same if you like.

**Comment by deepaklorkhatri007** [comment]
@Nalinc I am working on a new table of content design, it is based on the lanyon (a jekyll theme) but with bootstrap :)
![aima](https://user-images.githubusercontent.com/20015794/54637894-be109200-4aaf-11e9-8b1d-b2a6449e7127.gif)

**Comment by deepaklorkhatri007** [comment]
> that helped me a lot in understanding why the technologies which are currently being used in Aimacode Exercises were adopted in first place.

@sachin10101998 thanks for the suggestion buddy :)

**Comment by deepaklorkhatri007** [comment]
hey @Nalinc, I have updated the table of content code now it is using a YAML file which is easy to edit whenever we need a new exercise we can just slide it in the file and Jekyll will render the sidebar with new content, please provide your valuable feedback to this :)
![sidebar](https://user-images.githubusercontent.com/20015794/54716782-93d8d600-4b7c-11e9-8678-dbe792cdb225.gif)

**Comment by sachin10101998** [comment]
Hi @Nalinc , I was looking for ways to automate the process of addition of new exercises and answers without having to use Github and Netlify or Blot seems to be a plausible solution for the same. The instructors can just add the questions and they will get updated on the website. Should I build a sample site hosted on blot or Netlify to show the process?

**Comment by sachin10101998** [comment]
Hi @Nalinc, one of the prime objectives of GSoC 2019 is to refine the mechanism for showing answers. Can you throw some light over this statement? What exactly do you mean by refining the mechanism and what shortcomings are being faced by the current mechanism?

**Comment by deepaklorkhatri007** [comment]
> YAML is a sensitive language in the sense that a single extra space can render the file invalid.

@sachin10101998 I am using YAML for storing the table of content of the book which is done using an HTML (~/_includes/toc.html) file before and YAML file makes it easy to update/add/delete the table of content with new book revisions :)

**Comment by deepaklorkhatri007** [comment]
Hey @Nalinc, I have created a repo for the prototype I  am working on here is the link https://deepaklorkhatri007.github.io/aima-exercise-prototype/
can you please take a look at the site and help me improve the design for better user experience thank you :)
![designupdate](https://user-images.githubusercontent.com/20015794/54785151-7d4d8000-4c4b-11e9-81d5-e9e895b54eb2.gif)

**Comment by sachin10101998** [comment]
Hi @Nalinc,  Working on Chapter mode view sample with commenting enabled without user registration. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34926285/54875907-328b5e00-4e2d-11e9-9830-cb0f2b5381b7.gif)

**Comment by Nalinc** [comment]
@sachin10101998 Your UI-design is impressive, but our core focus is not just on making a pretty website, but to build a robust platform with an elegant interface (too many things can confuse potential visitors). In your most recent message above, where are user-comments being saved?

@deepaklorkhatri007 I liked your TOC design and the suggestion to use [gh-comments](https://github.com/wireddown/ghpages-ghcomments). Can you check if gh-comments can be used everywhere we are using Disqus threads on [aima-exercises](http://aimacode.github.io/aima-exercises)?

**Comment by deepaklorkhatri007** [comment]
> Can you check if gh-comments can be used everywhere we are using Disqus threads on [aima-exercises](http://aimacode.github.io/aima-exercises)?

@Nalinc yes we can use gh-comments on every chapter and exercises page and we can customize the comment panel using our own css that means we can give the comment section a similar look to our site

Also to make it easy for others to edit the markdown files (online) we can link [Prose](http://prose.io/) to our organization Prose is an opensourse github application which provides good markdown editor on the go :)

**Comment by deepaklorkhatri007** [comment]
Hey @Nalinc, I have included some bootstrap tooltip and modal code in my prototype repo please provide your valuable suggestions on how I can improve upon this [AIMA-Exercise Prototype](https://deepaklorkhatri007.github.io/aima-exercise-prototype/)
![tootipmodal](https://user-images.githubusercontent.com/20015794/54943901-4da6bc80-4f58-11e9-9b03-deb46cffec95.gif)

**Comment by Nalinc** [comment]
@deepaklorkhatri007 I like your prototype. Fixing references is one of the important tasks. Keep in mind that proposals will be evaluated based on 'how deep' and 'how thoughtfully' such issues are addressed.

**Comment by sachin10101998** [comment]
Hi @Nalinc  I read a blog where the author used "moderated comments" at the cost of real time discussion. He created a _comments directory with a hierarchy inside and populated it with YAML comments.  The hierarchy can be used to store comments from different pages. Each file in _comments represented  a single comment, as a YAML hash. The YAML contained a post_id attribute, which corresponds to the id of the post it is a comment on. The fields in YAML file were mapped to fields in a Comment object. There is a new page. comments field, which contains a list of the Comment objects for each post.  We can iterate through comments using a simple for loop. The order of the comments list returned in the page. comments array is based on the lexical ordering of the filenames that the comments are stored in. Hence, we can preserve strict date ordering of comments by ensuring that the filenames are based around the date/time of comment submission. The comments were received over email using PHP script which takes comment from a user, dumps it into YAML format and sends to pre-submitted email id of the moderator.  The documentation of the above can be found[ here. ](https://github.com/mpalmer/jekyll-static-comments) . 
THE TRICK:  The trick is to use the above documentation but instead of getting comments over email we use AWS Lambda or google cloud functions combined with Github API. In case we get lots of comments we can run the function on three platforms and round robin the DNS to take advantage of free use tiers on these sites. Litlle changes to liquid template will be required for rendering the comments to different pages. I used this in creating the above comments box but it was limited to one page only and hasn't been scaled properly. 
![Screenshot (332)](https://user-images.githubusercontent.com/34926285/54952615-6ae58600-4f6c-11e9-98f1-2153b82f7da5.png)
Each comment with usique ID.
and for rendering comments
![Screenshot (333)](https://user-images.githubusercontent.com/34926285/54952758-bdbf3d80-4f6c-11e9-80a8-4fa7e2e0f03a.png)

**Comment by sachin10101998** [comment]
Hi @Nalinc 
A quick question. 
The number of exercises in a few chapters is lesser than the number of exercises in the pdf of the book.
For example, Chapter 16 shows 28 exercises and the book ([Link](https://faculty.psau.edu.sa/filedownload/doc-7-pdf-a154ffbcec538a4161a406abf62f5b76-original.pdf)) has only 18. Why this anomaly?
Most of the questions I was having doubts about are not present in the book. For example, Chapter 16 exercise 16.8 and 16.9 mentions an "allais page". How should we proceed in finding correct references to such "allaiss page"," , given the fact that the book doesn't even have any such question and no reference has been provided on the production page?

**Comment by sachin10101998** [comment]
Contrary to last year, since this year the framework of Jekyll is fixed and we are using Github pages for hosting it, taking ideas from Nalin's table last year I am making a table referencing the various features that need to be implemented this time. Since the number of days are limited @deepaklorkhatri007  and I should work on different features so that the range of tested features can be maximized. Am updating the table based on the features @deepaklorkhatri007 and I are working on. Adding two extra columns in case some other contributors show up. @deepaklorkhatri007  if you want any of the columns to be updated or wish to work on other technologies, please drop a  message.

| Feature                     | Sachin | Deepak | x  | y  |
|-----------------------------|--------|--------|---|---|
| UI Design                   |    ✓     |  ✓       |   |   |
| Commenting system           |     ✓    |        |   |   |
| Proposing questions feature |        |        |   |   |
| Automating Questions addition without github |        |    ✓    |   |   |
| Bookmarking Questions                 |         |         |   |   |
| Cross referencing |   ✓     |    ✓    |   |   |
| Improving show answer mechanism             |   ✓       |         |   |   |
| Extracting Questions as PDF|          |         |   |   |
| Load test measurements |          |         |   |   |

**Comment by deepaklorkhatri007** [comment]
> For example, Chapter 16 shows 28 exercises and the book ([Link](https://faculty.psau.edu.sa/filedownload/doc-7-pdf-a154ffbcec538a4161a406abf62f5b76-original.pdf)) has only 18. Why this anomaly?

actually, he used questions from both US and international edition of the book that means you'll find more questions on the site like we have 40 questions in chapter 4 on the website but in my copy of Indian edition of the book I have only 37.

**Comment by deepaklorkhatri007** [comment]
> Fixing references are one of the important tasks

Hey, @Nalinc I have pushed a commit regarding Internal figure reference correction for Ex - 3.9, 3.19 and 14.6. we are using SVG images from Jupyter Notebook folder for the exercise and I think we should make a dedicated folder for all the assets we are using, the question.md file uses a direct link to [your GitHub repo for Aima Exercise](https://github.com/Nalinc/aima-exercises/tree/notebooks/Jupyter%20notebook/figures) which is not good if we ever have to shift the site to any other hosting service, what do you think?

**Comment by sachin10101998** [comment]
> 
> actually, he used questions from both US and international edition of the book 

You are right, but in order to make sure that anomalies don't arise due to different questions in different versions, I was referring to both the versions. But still couln't find the mentioned questions. However none of my references has 37 questions in Chapter 16. So I found the indian edition one and it has the required info for the given references.
For example "allais page" which I was earlier referring to is on page 620 according to one of the editions. But this info has not been given in Latex or markdown files.  I am assuming that @norvig would have uploaded all the exercise files in tex format.  So @Nalinc my question is which standard edition of the book should we refer to while addressing such references which mention a particular page. (screenshot attached) . 
![image](https://user-images.githubusercontent.com/34926285/54994840-4381ce00-4feb-11e9-8d29-71cf8c1d7aa1.png)

**Comment by sachin10101998** [comment]
@deepaklorkhatri007 I am quoting Nalin's words here regarding shifting AIMA Exercises to some host other than Gh-pages.
> Consider the deep learning book and its exercises for instance (I strongly recommend going through it as it is by some of the elite people in AI/DL community). Now re-imagine AIMA (the book) and AIMA-Exercises and what things should be there. You'll quickly understand that building a Django application with a full-fledged database would be an overkill for this task (plus we do not want to bear server/backend costs but the site needs to support heavy traffic too). Therefore, Github Pages+Jekyll has to be the only option. 

Hope it helps.

**Comment by deepaklorkhatri007** [comment]
> I am quoting Nalin's words here regarding shifting AIMA Exercises to some host other than Gh-pages.

@sachin10101998 there I was just proposing my idea that we should put all the assets like CSS, Javascript and Images in one folder and call them from there only.

**Comment by sachin10101998** [comment]
Hi @Nalinc One of the important tasks in updating cross-references is the linking of page references and the desired action is to jump to the page but the ebook version will not be available freely on GitHub I suppose, then what page are you referring to when you mentioned "Jump to page" as the desired action?

**Comment by Nalinc** [comment]
> The number of exercises in a few chapters is lesser than the number of exercises in the pdf of the book.
There are two reasons for this. First, as Deepak mentioned, we used questions from both US and international edition of the book. Second, AIMA Exercises are meant to support the 4th edition of the book (which has not been released yet). The book is expected to launch later this year and it will not have any exercise questions. Now coming to your next question,

> which standard edition of the book should we refer to while addressing such references which mention a particular page. 
For now, you may refer the 3rd edition on the book for such cases, but make sure you make a (tabular) list of all such exercises. @norvig and some other people are still working on the book. Once that is finalized, we will update those references.

> the ebook version will not be available freely on GitHub I suppose, then what page are you referring to when you mentioned "Jump to page" as the desired action?
"Jump to page" might not be possible to implement at this stage (since the book is still a work-in-progress). Till then, we can just show the "page number" as a tooltip as Deepak showed in his demo.

**Comment by Nalinc** [comment]
@sachin10101998  @deepaklorkhatri007 gh-comments looks promising, but since it stores comment-threads under the Github issues, it will potentially open 100+ issues on the GitHub repository which will further increase with the addition of new exercises. Considering this, I do not think it'll be ideal to go with gh-comments as is. One possibility is to store comments in a separate directory (_comments) and programmatically update comments discussions through a Github application (possibly on heroku). Not all Jekyll plugins are compatible with gh-pages, so [jekyll-static-comments](https://github.com/mpalmer/jekyll-static-comments) might not be directly usable. Improving just the discussion support would be a challenging task, but once done, it'll be really useful and remove our dependency from Disqus.

**Comment by sachin10101998** [comment]
@Nalinc Thank you for answering the queries.
>gh-comments looks promising, but since it stores comment-threads under the Github issues, it will potentially open 100+ issues on the GitHub repository
That's the sole reason why I was looking for alternatives to gh-issues and gh-comments. The presence of so many opened issues will be counterintuitive. I'll look for alternatives to Jekyll static comments or if possible would try to program them myself.

**Comment by sachin10101998** [comment]
Hi @Nalinc while looking for alternatives to Jekyll-static-comments, I stumbled upon '[Staticman](https://staticman.net/docs/)'  which brings user-generated content to statis sites like commenting system, voting system or a reviews section. 
Staticman converts data files into YAML and commits them to the main branch in places where they are needed either by creating a pull request (if moderation) is enabled or directly on its own if moderation is turned off. 
![Screenshot (337)](https://user-images.githubusercontent.com/34926285/55221565-bed3c180-522f-11e9-8a59-06c8c7e115f5.png)

**Comment by AkshitOstwal** [comment]
Hey I was thinking to take part in GSoC this year with this project , but it seems like @sachin10101998  and @deepaklorkhatri007  have already started doing work , and i am late here...
are you both also applying for the GSoC this year??
if yes , can i still apply here , are there any chances of selection

**Comment by sachin10101998** [comment]
>are you both also applying for the GSoC this year

Hi @AkshitOstwal , I will be applying for GSoC 2019.
>can i still apply here

Yes, GSoC programme is open for everyone and deadline for proposal submission is 9th April 2019.

>are there any chances of selection

@Nalinc is the mentor for AIMA Exercises and he can best answer this. However, till he replies you can go through the [GSoC Proposal template 2019](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-Proposal-Template) and [GSoC Onboarding Tasks ](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-On-boarding-Tasks) .

**Comment by Nalinc** [comment]
Hi @AkshitOstwal 

Checkout the wiki pages on this repository as mentioned by Sachin above. Most of the GSoC 2019 related discussions are happening on this thread. Read the previous messages and follow the steps. Selection will depend upon your contributions and the quality of your proposal.

@sachin10101998 Staticman seems awesome, but since it requires push access to a bot, I'd recommend putting up our own bot for this purpose. See if it can be deployed as an Heroku application. We have a firebase application for AIMA Exercises API (http://aima-exercises.firebaseapp.com) which essentially runs on google cloud functions. If staticman can be deployed on Heroku, we might shift the APIs on that instance too.

**Comment by sachin10101998** [comment]
>See if it can be deployed as an Heroku application. 

Already on it. @Nalinc 

>If staticman can be deployed on Heroku, we might shift the APIs on that instance too

Heroku gets costly fast. It does offer free starter dynos, however, ties developers into monthly payments in unexpected ways.

**Comment by sachin10101998** [comment]
>See if it can be deployed as a Heroku application.

@Nalinc Yes, it can be deployed as a Heroku application.  Cloning the repo of Staticman, setting up heroku account, configuring the RSA Private key for the encryption of secrets so that they can be published. To publish JSON config file _config.production.json_ ,we can store the secrets with environment variables, and access them with _process.env_ in JSON file and Node.js code. Next step would be setting up variable for GITHUB_TOKEN, GITLAB_TOKEN, RSA_PRIVATE_KEY and NODE_ENV.
JSON Config file:
![image](https://user-images.githubusercontent.com/34926285/55268732-8f19cd80-52b2-11e9-9d5a-1196cfe491f6.png)
Creating production branch from remote branch dev.
![image](https://user-images.githubusercontent.com/34926285/55268748-cb4d2e00-52b2-11e9-8ff5-8df87543205c.png)
Final step would be deployment to server. I have the full documentation on how to do this. 

>I'd recommend putting up our own bot for this purpose.

We can run our own instance of the application. We can make use of [Dokku](http://dokku.viewdocs.io/dokku/), which is a privately hosted Heroku replacement without all the limitations on the free tier. Staticman docs refer to the SSH key and RSA private key interchangably. They expect you to create it using _ssh-keygen_ per the Github docs, but the _config_ looks for it under _rsaPrivateKey_ in the application, or _RSA_PRIVATE_KEY_ in the environment. Staticman follows the 12 Factor approach to config, and so stores sensitive keys, etc, in the environment. We can supply all the environment variables and deploy the application. 
This would be done on a new github account. Now we can invite our new Staticman Github user as a collaborator on our current repo. And we would be good to go.

**Comment by sachin10101998** [comment]
@Nalinc One of the potential tasks you mentioned is the implementation of unit tests either as separate test-scripts or pre-commit hooks to ensure that the future changes in AIMA Exercises follow the right structure and cover essential things.
Could you throw some more light over what exactly is meant by this statement or what exactly do you mean by "to ensure that the future changes in AIMA Exercises follow the right structure and cover essential things"?

**Comment by deepaklorkhatri007** [comment]
> bookmarking particular questions by storing them in Local Storage of browser.

Hey, @Nalinc I have completed this task here is a demo
![bookmark](https://user-images.githubusercontent.com/20015794/55280617-17997c00-534e-11e9-84f5-bcc9a03a4f08.gif)




> are you both also applying for the GSoC this year??

yes, @AkshitOstwal I am participating in the GSoC this year. actually, I have already uploaded my proposal for @Nalinc to give feedback on.



> gh-comments looks promising, but since it stores comment-threads under the Github issues, it will potentially open 100+ issues on the GitHub repository which will further increase with the addition of new exercises.

yeah, I will check if we can generate our comments in _comments with this :)

**Comment by sachin10101998** [comment]
@Nalinc  Since the technology stack for most of the tasks to be implemented has been discussed, I am starting work on prototypes now. Will be adding all the other proposed features to the shown design soon.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/34926285/55290178-76fa9900-53ed-11e9-9185-d1c62d88abbf.gif)

**Comment by deepaklorkhatri007** [comment]
Hey, @Nalinc I have submitted a draft proposal on the GSoC site for this project, can you please take a look at my proposal and help me improve it.

**Comment by namanchikara** [comment]
Hello guys! I am Naman and I want to take part in GSoC through this project. My interests and skills are aligned with what this project is looking for. Can the mentors guide me what things are needed to be done to get accepted in GSoC?

**Comment by sachin10101998** [comment]
@namanchikara Hello Naman, please go through the [GSoC Proposal template 2019](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-Proposal-Template) and [GSoC Onboarding Tasks ](https://github.com/aimacode/aima-exercises/wiki/GSoC-2019:-On-boarding-Tasks) . Most of the GSoC discussions are limited to this thread only. Please go through the above thread and you'll easily find out what things are already done and what still require attention. 
Note: @Nalinc is the mentor for the project.

**Comment by namanchikara** [comment]
Alright, Thanks @sachin10101998 . I'll look into it.

**Comment by sachin10101998** [comment]
I started reading about load test measurements and technology stack related to it. I studied the documentation of JMeter and Locust. 
1) JMeter is written in pure Java Language. nowadays it allows testing almost any application and protocol, enabling users to create tests by using a desktop application that is compatible with any OS platform.
2) Locust is written on Python. It allows users to write performance scripts in pure Python and is highly scalable.
3) The JMeter GUI mode provides a desktop client that allows you to easily create tests without having to write a single line of code (until we need to create a tricky test). But if we need to, we can use a code, both in its GUI and in non-GUI mode, with Java.
4) Locust, on the other hand, does not provide an automatic testing feature and we have to write the scripts ourselves.
5) With JMeter, we can use a full arsenal of built-in functions and third-party plugins to create performance tests for everything in one place. We can test different protocols or even databases without any coding. These include JDBC, FTP, LDAP, SMTP, and many others.
6) Locust was built mainly for HTTP web based testing. However, you can extend its default functionality and create a custom Python function to test anything that can be tested by using the Python programming language.

7) Important Point: For the number of concurrent users test, JMeter and Locust use completely different mechanisms. JMeter running in GUI mode for the same scenario takes almost in 30x more memory than a Locust script. The implementation differences allow the Locust framework to easily simulate thousands of concurrent users on a single machine, even on a very regular laptop, while running complex tests with many steps inside.
![image](https://user-images.githubusercontent.com/34926285/55638042-f0c2c600-57e3-11e9-882b-b50ba8b07327.png)

Jmeter 
![image (1)](https://user-images.githubusercontent.com/34926285/55638058-f8826a80-57e3-11e9-8b6c-8dd58357a315.png)

Locust. 
8)Spike Load test: Both tools provide relatively the same way to generate loads for spike load test. But JMeter also has additional plugins that enable us to configure a very flexible load.
9) JMeter has a strong advantage, as it has built-in functionality for script recording, while Locust doesn't have this feature at all.

A table summarising the above results is attached at last.
I'd recommend using a mixture of these platforms for testing different parts of the website. 
@Nalinc  Let me know your views about it. 

References: [Link 1](https://www.blazemeter.com/blog/jmeter-vs-locust-which-one-should-you-choose),  [Link 2](https://www.merixstudio.com/blog/performance-testing-jmeter-and-locust/), [Link 3](https://stackoverflow.com/questions/43628194/what-is-implementation-option-in-jmeter-and-how-it-actually-works), [Link4](https://jmeter.apache.org/usermanual/index.html), and few pages on StackOverflow. 


|                            | JMeter                                                  | Locust                  |
|----------------------------|---------------------------------------------------------|-------------------------|
| Operating System           | Any                                                     | Any                     |
| Open Source                | Yes                                                     | Yes                     |
| GUI                        | Yes, with non-GUI mode available                        | No                      |
| Execution Monitoring       | Console  File  Graphs  Desktop client  Custom plugins   | Console Web             |
| Support of “Test as Code”  | Weak (Java)                                             | Strong (Python)         |
| In-built Protocols Support | HTTP  FTP  JDBC  SOAP  LDAP  TCP  JMS  SMTP  POP3  IMAP | HTTP                    |
| Integrated Host Monitoring | PerfMon                                                 | No                      |
| Recording Functionality    | Yes                                                     | No                      |
| Distributed Execution      | Yes                                                     | Yes                     |
| Easy to use with VCS       | No                                                      | Yes                     |
| Resources Consumption      | More resources required                                 | Less resources required |
| Number of Concurrent Users | Thousands, under restrictions                           | Thousands               |
| Ramp-up Flexibility        | Yes                                                     | No                      |
| Test Results Analyzing     | Yes                                                     | Yes                     |

**Comment by sachin10101998** [comment]
Hello @Nalinc Recently, some user named 'harriis' requested solution for exercise 7.28. I submitted PR for adding a solution to the concerned exercise.
He requested for the solution twice for some reason. He seems to be legit but the incident is a subtle nod to the need for a mechanism to check if the answer has already been requested or not. For example, lots of people may request answer for a particular exercise creating lots of duplicate issues in the repository or someone may keep sending the request for an answer for a particular exercise thereby spamming this repository with duplicate issues. 
I looked at the mechanism and found that the button for requesting answer redirected the user to create a new issue with pre-defined title issue. Using JS and Github Issue search API we can prevent the user from creating a new issue if the issue already exists by matching the title of already existing issues. This would be a small modification but really useful for a legit visitor to check if the answer has already been requested. 
Do you think to match the title of issues is an optimal solution for solving the problem of duplicate issues being created for requesting an answer to the same exercise?
If yes, should I work on this PR to avoid duplicate spam issues in the repository?
